name: "Build and Test NodeJS"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: "npm run coverage && npm run report:lcov"
      - uses: codecov/codecov-action@v3
        with:
          flags: unittests # optional
